import {
  CreditCardIcon,
  DocumentCheckIcon,
  ShoppingCartIcon,
} from "@heroicons/react/24/outline";

export function Features({ theme }: { theme: "normal" | "shopify" }) {
  const features = [
    {
      name: "Available domains only",
      description:
        "We check with GoDaddy to make sure that all of the domain names we suggest to you are available. We don’t want to waste your time.",
      icon: DocumentCheckIcon,
    },
    theme === "shopify"
      ? {
          name: "Buy direct from Shopify",
          description:
            "When you’ve found the perfect domain name for your new Shopify store, we’ll take you straight to Shopify’s website to finalise your purchase. Keep everything in the same place.",
          icon: ShoppingCartIcon,
        }
      : {
          name: "Multiple registrars",
          description:
            "We don’t expect you to use the same registrar as we do. That’s why we give you the option to buy your perfect domain name from Namecheap, Domain.com, Google Domains, GoDaddy and bluehost.",
          icon: ShoppingCartIcon,
        },
    {
      name: "No credit card required",
      description:
        "Recommend Domains is 100% free and always will be. If you’d like to support the site, starring the GitHub repository would be very much appreciated!",
      icon: CreditCardIcon,
    },
  ];

  return (
    <section className="bg-gray-900 py-32 sm:py-48 lg:py-56">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-3xl lg:text-center">
          <p className="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">
            Generated by artificial intelligence
          </p>
          <p className="mt-6 text-lg leading-8 text-gray-300">
            We use{" "}
            <a
              className="text-primary-400 rounded focus:outline-none focus-visible:outline-2 focus-visible:outline-primary-200"
              href="https://openai.com/blog/chatgpt"
              target="_blank"
            >
              ChatGPT
            </a>{" "}
            to generate the perfect domain name for your{" "}
            {theme === "shopify" ? "Shopify store" : "website"} and we’ll check
            the domain name with{" "}
            <a
              className="text-primary-400 rounded focus:outline-none focus-visible:outline-2 focus-visible:outline-primary-200"
              href="https://www.godaddy.com/en-uk"
              target="_blank"
            >
              GoDaddy
            </a>{" "}
            to make sure that it’s available.
          </p>
        </div>
        <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-none">
          <dl className="grid max-w-xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-3">
            {features.map((feature) => (
              <div key={feature.name} className="flex flex-col">
                <dt className="flex items-center gap-x-3 text-base font-semibold leading-7 text-white">
                  <feature.icon
                    className="h-5 w-5 flex-none text-primary-400"
                    aria-hidden="true"
                  />
                  {feature.name}
                </dt>
                <dd className="mt-4 flex flex-auto text-base leading-7 text-gray-300">
                  {feature.description}
                </dd>
              </div>
            ))}
          </dl>
        </div>
      </div>
    </section>
  );
}
